apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms.name" . }}-configmap
data:
  application.properties: |
    app.test.name="Passed-in-name"
    config.value1={{ .Values.microservice.config.field1 }}
    config.value2={{ .Values.microservice.config.field2 }}
    config.value3={{ .Values.microservice.config.field3 }}