apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms.name" . }}
  labels:
    {{- include "ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}90
      targetPort: 8090
      nodePort: 30007
      name: external
  selector:
    {{- include "ms.selectorLabels" . | nindent 4 }}
